server:
  port: 8888

app:
  api-prefix: /shop/v1

spring:
  application:
    name: api-gateway

  data:
    redis:
      host: localhost
      port: 6370
      password: ${REDIS_PASSWORD}
      timeout: 2000

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: authentication-service
              uri: http://localhost:8000
              predicates:
                - Path=/shop/v1/auth/**
              filters:
                - StripPrefix=2

            - id: user-service
              uri: http://localhost:8080
              predicates:
                - Path=/shop/v1/users/**
              filters:
                - StripPrefix=2

            - id: notification_service
              uri: http://localhost:8081
              predicates:
                - Path=/shop/v1/notification/**
              filters:
                - StripPrefix=2

            - id: product-service
              uri: http://localhost:8082
              predicates:
                - Path=/shop/v1/product/**
              filters:
                - StripPrefix=2

            - id: order-service
              uri: http://localhost:8083
              predicates:
                - Path=/shop/v1/order/**
              filters:
                - StripPrefix=2

            - id: payment-service
              uri: http://localhost:8084
              predicates:
                - Path=/shop/v1/payment/**
              filters:
                - StripPrefix=2

            - id: cart-service
              uri: http://localhost:8085
              predicates:
                - Path=/shop/v1/cart/**
              filters:
                - StripPrefix=2

            - id: search-service
              uri: http://localhost:8087
              predicates:
                - Path=/shop/v1/search/**
              filters:
                - StripPrefix=2

            - id: chatbot-service
              uri: http://localhost:8088
              predicates:
                - Path=/shop/v1/chatbot/**
              filters:
                - StripPrefix=2